### ISSUE TITLE
Editing custom settings (issue and question)

### ISSUE THREAD

**Issue by madysondesigns** [frankko/Artboard-Tools#22]
Hello-

I'm trying to customize the `use_slashes` ~and `spacing_x`/`spacing_y`~ options for my workflow, and the plugin doesn't seem to ~reflect my new settings when using the Group Artboards (Rows) tool~ work as expected. 

What I did: 
- Edited via Reveal in Finder > Show Package Contents > edit `ArtboardTools.js` values
- ~Restarted Sketch~
- ~Disabled and re-enabled plugin~

Some more info:
- I'm on Sketch 52.2. 
- It seems to order and break rows based on naming and order in the layer palette -- if the artboards that should group are together, it works, but not if the order is mixed. 

Bonus question: Do these custom settings persist after a plugin update through Sketch's update mechanism? If not, that would be a great enhancement (or even better, an options page).

**Comment by madysondesigns** [comment]
~Follow-up: I figured out the issue with `spacing_x`/`spacing_y` -- it's defined in multiple places in the file.~

User error. It would be nice to have these defined once at the root of the object.

**Comment by frankko** [comment]
* putting `spacing_x` and `spacing_y` in the root object:

I’ll look into that

* will custom changes persist after a plugin update? 

Not currently, no. I don’t think there’s built-in way via Sketch to have something like that persist, which means I’d need to do something on the OS level, which might be a too complicated a task given my current work load. But I’ll see what I can do.

**Comment by madysondesigns** [comment]
Thanks for that info. (based on my cursory research, it looks like Sparkle's updater includes delta functionality, so maybe it can be as simple as two separate files?)

But, there is still a problem with `use_slashes` and naming vs. layer order. If it helps, I can provide an example file.

**Comment by frankko** [comment]
Oh, sorry. Yeah a sample file will be great. All I really need are empty artboards that are named like you have them named. frank at kolo dot io

**Comment by frankko** [comment]
Thanks for the sample file. Unless I’m missing something, I think the problem is that the plugin, as part of the arranging process, doesn’t sort the artboards by name, but rather goes by the order they are in the Layer List. So if you have a few artboards that start with 21, then 20, then 11, then 30, it won’t sort them to 11, 20, 21, 30 before arranging them. They’ll stay in the order they are.

Sorting layers as part of the arranging has been requested before, but I’m probably not going to add that any time soon, if ever. (Primarily I don’t want to assume that everybody that uses the plugin wants their layers sorted.)

There’s a plugin called Sort Me that I use to sort my artboards when I need to that you could look into. There might be others, as well.

**Comment by madysondesigns** [comment]
Ah, I was under the impression that the plugin would arrange/group by name, independent of the order in the layers palette – I don't think it's clear in the readme that it depends on that order as well. 

I don't need it to reorder them, but I do need to arrange them visually. If that's not the intended functionality, then I can just use Sort Me to order them before arranging. Thanks! 

(eta: confirmed, if I use Sort Me first this works exactly as I'd expect/need 😄)
