### ISSUE TITLE
View Actual Size

### ISSUE THREAD

**Issue by philipp-lehmann** [frankko/Artboard-Tools#5]
It would be nice to include an option to keep the scale at 100%.
This can be than including the following code:

[view centerRect:[target_artboard rect]];
[view actualSize];

But i have no idea how to achieve this without duplicating the whole function.

**Comment by frankko** [comment]
Actually, I think the better thing to do would be to preserve the zoom. If you were at 200%, 100%, zoomed to fit, whatever, after switching artboards, it should jump back to that. That way I’m not forcing a change of zoom on the user, whether it’s scaled to fit or 100%.

I had that in there for a bit during testing but Sketch only did it half the time so I took it out. That was Sketch 3.2. I’ll try it again on both Sketch 3.3 and the Sketch 3.4 beta to see if it’s gotten any better.

**Comment by toorshia** [comment]
Actually, I almost always use your cmd + 4 followed by cmd + 0 to zoom to actual size :)
I am trying to modify your script to trigger actual size zooming after zoomToFit (I know it's stupid and hacky - I am just trying out things), but so far neither [view actualSize] nor doc.zoomValue = 1 are working. Can you help out? :) How can I trigger zoom to actual size instead of zoom to fit in your script?

**Comment by frankko** [comment]
find 

```
doc.actionsController().actionForID("MSZoomToSelectionAction").zoomToSelection(nil);
```

and replace it with

```
doc.actionsController().actionForID("MSZoomToActualSizeAction").actualSize(nil);
doc.actionsController().actionForID("MSCenterSelectionInVisibleAreaAction").centerSelectionInVisibleArea(nil);
```

I just tried it and it works, but I haven’t thoroughly tested it, use at your own risk, etc etc.

**Comment by toorshia** [comment]
Thanks for the quick reply! Centering is not working for me, but if I hit cmd + 4 once more, than it centers hahahaha ;)
