### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by custa1200** [frankko/Artboard-Tools#8]
Tried to use the Group artboards in Sketch 3.9b5 and it did nothing. i did change the separator for dartboards from -- to / though as that seems to be the separator type Sketch has finalised on. a plugin like this is sorely needed with the advent of symbol artboards to deal with nested symbols.

**Comment by frankko** [comment]
Sorry, what did you change?

I’ve been using the release version in Sketch 39 with no problems. I chose ‘--‘ originally to not conflict with ‘/‘, as the / will create directories if you export your artboards. I didn’t want people to have to force their artboards into directories to group them, so I used something else.

If you show me what you did, I might be able to figure out why it isn’t working for you.

**Comment by guzforster** [comment]
Not working for me either. I changed the separator in the variable to "true" in order to use slashes, the plugin "works", but it's not organizing the artboards properly. I have three artboards like "name1 / option1", "name1 / option2" etc and it only organizes some of them and others it doesn't - right now it's looking random but I don't know. Using Sketch 43.2 btw.

**Comment by frankko** [comment]
@guzforster the only thing I can think of here is if your artboard names have multiple slashes in them. For example:

1. name 1 / option 1
1. name 1 / option 2
1. name 2 / option 1
1. name 3 / option 1
1. name 3 / option 2
1. name 3 / option 2 / variant 2
1. name 3 / option 2 / variant 3

That would group them like so:

1 2
3
4 5
6 7

Even though 5 and 6 both have “name 3 / option 2” in them, the way the pattern matching works, the last / in a name is what gets matched. So for 5, the plugin thinks the group is called “name 3” while in 6 it thinks the group is named “name 3 / option 2”. If that makes sense.

Another possibility, which is mentioned in the Readme, is that the plugin groups by layer order, from the bottom up. If your layers look something like this:

- name 1 / option 1
- name 2 / option 1
- name 1 / option 2

That’ll put each artboard on its own row. The plugin doesn’t scan all the layer names and try to find similar names. It starts at the bottom of the layer list and moves up, one artboard at a time, where it determines what it thinks the group name is for the current artboard, and compares that name to the artboard below, and it either starts a new row or doesn’t.

I don’t know if that helps. If you can give me a sample file, I could look into this further. All I would need is a file with a bunch of empty artboards that have the names you’re having trouble with. I don’t need to see what you’re working on.

**Comment by guzforster** [comment]
That is indeed what is happening. It is separating even by
1. name 1 / option1
2. name 1 / option2
3. name 1 / option3 2

It groups like
1 2
3 (because of two words)

Although it made sense after you explained, that doesn't make too much sense for organizing... Still would be better (for me at least), if it separated by the first name before the slash.

Thanks!
