### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mistcat** [frankko/Artboard-Tools#9]
Can you add a toggle to reverse the order of arrangement?  I have a bunch of artboards prefixed with A-Z type labels and this plugin seems to sort them Z-A... Otherwise super helpful, thank you!!

**Comment by frankko** [comment]
I’ll think about adding a reverse sort, it’s not a bad idea. But in the meantime, just to clarify, the plugin doesn’t sort based on name. It goes through the artboards as they are stacked in the layers list _from the bottom to the top_, which is the order provided by Sketch to plugins.

So if your artboard starting with the letter A is at the top of the list and Z is at the bottom, the plugin will place Z at the top left of the canvas because as far as Sketch is concerned it’s the first artboard.

**Comment by patrickrushton** [comment]
+1 for a reverse sort so that it goes through the artboards from top to bottom.

Reason? When a Sketch file is synced to Invision, it sorts the artboards from top to bottom.

**Comment by frankko** [comment]
Got it. I’ll see what I can do.
